### ISSUE TITLE
bug at shell example at readme.md

### ISSUE THREAD

**Issue by kazimsarikaya** [creack/pty#111]
we should close channel at defer function. other while for loop listening cannot stop.

**Comment by creack** [comment]
I updated the README closing the channel. However, I don't think that was related to your concern. The example is not meant to be a product, but rather a demonstration.

Running the code as-is in a loop will indeed result in the Stdin blocking until the next keystroke (added comment for that as well). You would need to create a pipe and pass that around instead of consuming os.Stdin directly.
