### ISSUE TITLE
SetReadDeadline is invalid for pty read, it will block

### ISSUE THREAD

**Issue by itmisx** [creack/pty#174]

**Comment by creack** [comment]
Would you have more details? context? way to reproduce?

**Comment by itmisx** [comment]
eg
```go
ptmx.SetReadDeadline(time.Now().Add(time.Second))
ptmx.Read(buf)
```
i set the read deadline one second, but if there is no new msg, the read will always block

**Comment by creack** [comment]
On what go version, what os/arch?

**Comment by creack** [comment]
Note that v1.1.21 reverted the non-block behavior introduced by #167, all os are now blocking, which mean SetReadDeadline will not work.

- On windows, non-block is not supported for the console.
- On OSX, non-block causes the read to use 100% CPU.
- On Linux, non-block causes races resulting in random silent failures of ioctl, read and write.

While there is nothing we can do about windows, if you believe it is really important, maybe we could add an optional flag or a different public method to use non-block on OSX and Linux.

Closing for now as it is an expected behavior.
