### ISSUE TITLE
Issues on the old repository were disabled

### ISSUE THREAD

**Issue by graywolf-at-work** [creack/pty#94]
Issues on the old repository (before move) are disabled which breaks all links with 404. Is it possible to re-enable them but still keep that repo read-only?

**Comment by kr** [comment]
Oh hm. I don't think there's a way to enable the issues without letting people also create new issues. But that may still be better than serving 404s…

**Comment by kr** [comment]
I just tested it: unarchiving the repository and enabling issues does not fix the problem. I think this is because the repo at kr/pty is a fork of creack/pty (this repo) and so it gets its own issue numbers. Once I made that fork, GitHub can't redirect issue links here any more, regardless of what settings are used in the fork.

I believe there is no way to fix this.

**Comment by kr** [comment]
It may not have been the best choice to transfer the repo to begin with. Maybe we should have copied the issues over to a new repo (either a fresh repo or a fork or the original) here. That would have had its own downsides, of course. I'm not sure which is better.

**Comment by kr** [comment]
I'm going to close this now, because I think there's nothing we can do about it. If you know of an alternative I haven't considered, please reopen this or make a new issue or something. Sorry about this!
